### ISSUE TITLE
Bug with apartments 3 and 4

### ISSUE THREAD

**Issue by sapiomr** [loiste-interactive/Obenseuer-Issues#1726]
Not sure what caused it but the 2 smaller apartments on floor 2 show low % clear and are inaccessible for renovation despite being cleared.

**Comment by Zuntti** [comment]
Can I get a save where this has happened?

**Comment by Zuntti** [comment]
Fixed

**Comment by DasCapschen** [comment]
This is not fixed. I am still experiencing this in 0.3.33  
It seems to happen when you start clearing Apartments before talking to the Renovation guy. 

Should anyone else stumble across this:
- go to `C:\Users\<Username>\AppData\LocalLow\Loiste Interactive\Obenseuer\Saves\<CharacterName>\<Slot>\`
- edit `Globals.tnmt`
- set `currentFurnitureAmountPrimary` and `currentFurnitureAmountSecondary` to 0 for the Apartment that is bugged. (the file is very big, use ctrl+f search! You can first search for `apartmentNumber` to find the correct apartment)

**Comment by Zuntti** [comment]
Can I get a save where this happens?

**Comment by DasCapschen** [comment]
Here you go. This is before I first talked to Samuel Jonasson, and before I cleaned out the apartments.    
The bug happens regardless, if I
- first talk to Jonasson, then clear apartments
- first clear apartments, then talk to Jonasson

[Slot2.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14387552/Slot2.zip)
