### ISSUE TITLE
Items stuck in stations

### ISSUE THREAD

**Issue by DFliyerz** [loiste-interactive/Obenseuer-Issues#1785]
Items are stuck in my lathe and chemical lab, which can't be claimed or cleared by picking up and re-placing the station. This happened before switching to the playtesting branch, but is continuing through the playtesting branch.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8572440/52514a3c-1a53-4a25-a830-d36805b434b8)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/8572440/73ff2072-d491-4162-a9f6-61f860b74da9)

**Comment by Oskutin** [comment]
Should be fixed already in playtesting

**Comment by DFliyerz** [comment]
I'm on the playtesting branch and it's still broken, even after turning it off/on, saving and loading, or picking it up and placing it again.

**Comment by DFliyerz** [comment]
Compost is stuck too now.

**Comment by DFliyerz** [comment]
[Alexander_Sokolov.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/14073739/Alexander_Sokolov.zip)
Here's my save file... I have absolutely no clue what happened but somehow I ended up with another lathe in my inventory along with the broken one? I didn't find a way to cheat one in and hadn't had a chance to cheat in some money to buy a new one so I have no idea where the other one came from. The chemical lab and compost are still broken though.
