### ISSUE TITLE
Wall clipping bug in the Deekula A6 storage (v. 0.3.38)

### ISSUE THREAD

**Issue by hauuau** [loiste-interactive/Obenseuer-Issues#2977]
If the player manages to jump on top of the rat cage structure in the Deekula A6 storage room by crouch jump then they'll get teleported behind the wall upon releasing crouch.

Game version: v. 0.3.38 (public).

**Comment by Oskutin** [comment]
fixed

**Comment by hauuau** [comment]
https://github.com/user-attachments/assets/b6aa3f92-5710-416b-984d-87ce76523f60

Seems to still happen on the latest playtest v. 0.3.47.
Even if not as easily as it was on public.
