### ISSUE TITLE
Carons in name inputs are not displayed

### ISSUE THREAD

**Issue by Unkrass** [loiste-interactive/Obenseuer-Issues#3500]
Czech characters like č, ď, ě, ň, ř, š, ť, ž are not displayed, when entering them in the name inputs. Found this in 0.4.0 after today's update.

![Image](https://github.com/user-attachments/assets/3ccf8d8c-c7dd-4dea-8642-775be9a9561e)

**Comment by Oskutin** [comment]
seems that this is already fixed by the introduciton of fallback fonts

**Comment by Unkrass** [comment]
> seems that this is already fixed by the introduciton of fallback fonts

in which version will the fallback fonts come? i'm on 0.4.01 and it's still happening
