### ISSUE TITLE
[V0.4.0] [Bug] The orange mushroom seller's inventory doesn't reset

### ISSUE THREAD

**Issue by dafirek** [loiste-interactive/Obenseuer-Issues#3548]
I filled the inventory of the mushroom seller in the mines, and after 1-2 weeks of waiting, he still has all the items. Additionally, every time I enter his home, I get the notification for discovering a new place.

**Comment by Oskutin** [comment]
fixed

**Comment by OstinFas** [comment]
Sorry to bother, but I might still have this issue in the current version.

[Slot5.zip](https://github.com/user-attachments/files/18596921/Slot5.zip)
[Slot9.zip](https://github.com/user-attachments/files/18596920/Slot9.zip)

Between those saves, I followed cv's advice and bought and resold all of Ivar's inventory and it hasn't refreshed after a couple of days. Is it supposed to take longer?
