### ISSUE TITLE
Player's apartment is marked "not examined" in the map though it has been examined and the building menu is available

### ISSUE THREAD

**Issue by CarlieBendix** [loiste-interactive/Obenseuer-Issues#508]
Loading save doesn't fix the issue

**Comment by Zuntti** [comment]
Fixed

**Comment by BurningButter** [comment]
I am still experiencing this issue (fully updated latest release on Steam)
