### ISSUE TITLE
Player stats get broken and the console keeps returning an error.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#522]
At some point the stats icons seems to be gone completely and the stats themselves sees to either not progress at all or do it very slowly, after like half an hour they did come back but were wrongly displayed (thirst was seen when it was only 4% of need) and were hardly progressing, then a reload broke them again.
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/e5a3fb80-6c05-4b88-aaa8-9fda082b38e1)
![image](https://github.com/loiste-interactive/Obenseuer-Issues/assets/44178400/c02b55a1-798d-4633-9016-34d3ca26ab42)
[Player.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/12466653/Player.zip)

**Comment by Nextej** [comment]
Seems like reloading whole game fixes them back, even on existing saves with that issue.

**Comment by Oskutin** [comment]
Fixed the error späm

**Comment by Kastuk** [comment]
Same bug strikes again after some playing, stats dussapear after loading of an location.
Stats will reappear if I got damage at green shrooms ir firing barrel.
But wrapper error still spamming the console.

**Comment by Kastuk** [comment]
I got this error again after some intesive farming in greenhouse, after exit to outside.
![20231030235815_1](https://github.com/loiste-interactive/Obenseuer-Issues/assets/36314945/2f72df7f-e63a-4e50-8e7d-7519b2dd9109)
No stats and addiction showing, console is emptz and when I enter _**player_stats get**_, I got repeating error.
[Player.log](https://github.com/loiste-interactive/Obenseuer-Issues/files/13209906/Player.log)

Autosave after exit and saveslot after error spam.
[no stats error spam.zip](https://github.com/loiste-interactive/Obenseuer-Issues/files/13209914/no.stats.error.spam.zip)
