### ISSUE TITLE
New Market issues

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Obenseuer-Issues#549]
Got so low fps there unlike in previous version.

Yeast cannot be placed back into freezer.

(wrong alarm)Cheese will disappear when placed back on shelf by hotkey F.

Freezer shelf of Prepared goods have Steal action and contain Stolen Meatballs, which not go into checkaout and not trigger alarm at exit.

**Comment by Kastuk** [comment]
Got wrong at cheese, they're just stacked.

**Comment by Oskutin** [comment]
Fixed

**Comment by snortico** [comment]
Prepared foods still cannot be purchased (or even eaten while 'stolen' prior to checkout.) They cannot be placed on the belt.
